name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "**/README.md"
      - ".github/renovate.json"
      - "renovate.json"
      - "renovate.json5"
  pull_request:
    paths-ignore:
      - "README.md"
      - "**/README.md"
      - ".github/renovate.json"
      - "renovate.json"
      - "renovate.json5"

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  go:
    uses: Tech-S1/ci-templates/.github/workflows/go-ci.yml@main
    with:
      build-packages: ./cmd/kiosk-display
